/****************************************************************************
**
** DCOP Skeleton generated by dcopidl2cpp from konjueiface.kidl
**
** WARNING! All changes made in this file will be lost!
**
*****************************************************************************/

#include "./konjueiface.h"

#include <kdatastream.h>


static const char* const KonjueIface_ftable[2][3] = {
    { "void", "displayVerb(QString)", "displayVerb(QString verb)" },
    { 0, 0, 0 }
};
static const int KonjueIface_ftable_hiddens[1] = {
    0,
};

bool KonjueIface::process(const QCString &fun, const QByteArray &data, QCString& replyType, QByteArray &replyData)
{
    if ( fun == KonjueIface_ftable[0][1] ) { // void displayVerb(QString)
	QString arg0;
	QDataStream arg( data, IO_ReadOnly );
	if (arg.atEnd()) return false;
	arg >> arg0;
	replyType = KonjueIface_ftable[0][0]; 
	displayVerb(arg0 );
    } else {
	return DCOPObject::process( fun, data, replyType, replyData );
    }
    return true;
}

QCStringList KonjueIface::interfaces()
{
    QCStringList ifaces = DCOPObject::interfaces();
    ifaces += "KonjueIface";
    return ifaces;
}

QCStringList KonjueIface::functions()
{
    QCStringList funcs = DCOPObject::functions();
    for ( int i = 0; KonjueIface_ftable[i][2]; i++ ) {
	if (KonjueIface_ftable_hiddens[i])
	    continue;
	QCString func = KonjueIface_ftable[i][0];
	func += ' ';
	func += KonjueIface_ftable[i][2];
	funcs << func;
    }
    return funcs;
}


